const dummyTransactions: Transaction[] = [
    {
      $id: '1',
      id: '1',
      name: 'Payment to Vendor A',
      paymentChannel: 'Credit Card',
      type: 'debit',
      accountId: 'acc001',
      amount: 500,
      pending: false,
      category: 'Groceries',
      date: '2024-12-19T14:30:00Z',
      image: 'image_url_1', // Example image URL
      $createdAt: '2024-12-19T14:00:00Z',
      channel: 'Credit',
      senderBankId: 'bank001',
      receiverBankId: 'bank002',
    },
    {
      $id: '2',
      id: '2',
      name: 'Payment from Client B',
      paymentChannel: 'Bank Transfer',
      type: 'credit',
      accountId: 'acc002',
      amount: 1200,
      pending: false,
      category: 'Services',
      date: '2024-12-18T09:15:00Z',
      image: 'image_url_2',
      $createdAt: '2024-12-18T09:00:00Z',
      channel: 'Bank',
      senderBankId: 'bank003',
      receiverBankId: 'bank004',
    },
    {
      $id: '3',
      id: '3',
      name: 'Payment to Vendor C',
      paymentChannel: 'Debit Card',
      type: 'debit',
      accountId: 'acc003',
      amount: 350,
      pending: false,
      category: 'Utilities',
      date: '2024-12-17T18:45:00Z',
      image: 'image_url_3',
      $createdAt: '2024-12-17T18:30:00Z',
      channel: 'Debit',
      senderBankId: 'bank005',
      receiverBankId: 'bank006',
    },
    {
      $id: '4',
      id: '4',
      name: 'Payment from Client D',
      paymentChannel: 'Cash',
      type: 'credit',
      accountId: 'acc004',
      amount: 800,
      pending: false,
      category: 'Consulting',
      date: '2024-12-16T20:10:00Z',
      image: 'image_url_4',
      $createdAt: '2024-12-16T20:00:00Z',
      channel: 'Cash',
      senderBankId: 'bank007',
      receiverBankId: 'bank008',
    },
    {
      $id: '5',
      id: '5',
      name: 'Refund from Vendor E',
      paymentChannel: 'Bank Transfer',
      type: 'credit',
      accountId: 'acc005',
      amount: 200,
      pending: false,
      category: 'Refund',
      date: '2024-12-15T12:00:00Z',
      image: 'image_url_5',
      $createdAt: '2024-12-15T11:45:00Z',
      channel: 'Bank',
      senderBankId: 'bank009',
      receiverBankId: 'bank010',
    },
  ];
  
  export default dummyTransactions;
  